title: Angel Adrian Pimienta Flores - Portfolio
description: iOS Developer and Computer Systems Engineering student showcasing projects in Swift, AR/VR, and AI
author: Angel Adrian Pimienta Flores
email: angel.pimientafs@udlap.mx
github_username: Githubense
url: "https://githubense.github.io"
baseurl: "/web"

# Build settings
markdown: kramdown
highlighter: rouge

# Remove theme line - using custom CSS instead
# theme: minima

# Include files
include:
  - _pages

# Exclude files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Portfolio settings
portfolio:
  title: "Portfolio"
  description: "A showcase of my work and achievements"

# Social links
social_links:
  github: https://github.com/Githubense
  email: angel.pimientafs@udlap.mx

# SEO settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub Pages specific settings
github: [metadata]