title: My Portfolio Website
description: A showcase of my work and achievements
author: Angel Adrian Pimienta Flores
email: angel.pimientafs@udlap.mx
github: https://github.com/Githubense
theme: glassmorphism
layout: bento-grid
portfolio_items:
  - title: About Me
    image: assets/images/about-bg.jpg
    video: null
  - title: Code
    image: assets/images/code-bg.jpg
    video: null
  - title: Education
    image: assets/images/education-bg.jpg
    video: null
  - title: Design
    image: assets/images/design-bg.jpg
    video: null
  - title: Achievements
    image: assets/images/achievements-bg.jpg
    video: null
  - title: Certifications
    image: assets/images/certifications-bg.jpg
    video: null
  - title: Skills
    image: assets/images/skills-bg.jpg
    video: null
  - title: Apps
    image: assets/images/apps-bg.jpg
    video: null
  - title: Contact
    image: assets/images/contact-bg.jpg
    video: null
social_links:
  linkedin: https://www.linkedin.com/in/yourprofile
  twitter: https://twitter.com/yourprofile
  instagram: https://instagram.com/yourprofile
  facebook: https://facebook.com/yourprofile